### PR TITLE
Load Psapi.dll at runtime, this avoids linking caveat

### PR DESCRIPTION
**Pull request by pali**

### CODE REVIEW

**Comment by pali** [comment]
AppVeyor failed on error:
```
fatal: unable to access 'https://github.com/dlfcn-win32/dlfcn-win32.git/': Could not resolve host: github.com
4
```
You can try to click on "re-run incomplete jobs".

**Comment by traversaro** [comment]
@pali done

**Comment by pali** [comment]
Great! Now tests passed.

**Comment by pali** [comment]
@traversaro can you look at this PR?

**Comment by traversaro** [comment]
Thanks for the PR, and sorry for the delay.

**Pull request merged**
