### PR TITLE
Add MinGW and MinGW-w64 builds to AppVeyor

### PR DESCRIPTION
**Pull request by pali**

### CODE REVIEW

**Comment by pali** [comment]
Just testing... will see if this works or not.

**Comment by pali** [comment]
Seems it does not work :-(

**Comment by pali** [comment]
Something is terrible broken...
```
  The C compiler
    "C:/MinGW/bin/gcc.exe"
  is not able to compile a simple test program.
```

**Comment by traversaro** [comment]
>  Something is terrible broken...

I am not sure why, but `gcc` seems to be working fine only if its directory is added to the PATH, see https://github.com/dlfcn-win32/dlfcn-win32/pull/48 .

**Comment by pali** [comment]
Great, you have fixed it. So closing this one PR.

**Pull request closed without merging**
