### PR TITLE
CMake build system fixes

### PR DESCRIPTION
**Pull request by rhabacker**
At #72 it has been requested to build the executable test-dladdr for checking present dladdr implementations on unix lik os. The associated cmake changes requires to exclude the library and some test executables, which is easier with this approach.

While working on this I recognized minor issues, which I fixed also with this pr with the commit 242f781`Fix cmake warning 'No project() command is present'`

### CODE REVIEW

**Comment by pali** [comment]
This looks like a big and significant change in project directory structure and building procedure. I will let this PR to project maintainer @traversaro.

**Comment by traversaro** [comment]
Hi @rhabacker , can you specify what this PR is suppose to "fix" at the CMake level? As far as I can see it is just a refactor of the CMake script, and I am not sure what is the aim. In any case, the library and tests `.h`/`.c` are referenced also by other build systems in the repo (`make`/`vxproj`) so we need either to update also them, or to avoid to move the `.h`/`.c` files.

**Comment by rhabacker** [comment]
> vxproj

Just a question: Why are you maintaining this additional build system when you can use cmake to generate this on the fly ?
```
cmake.exe --help

Generators

The following generators are available on this platform (* marks default):
  Visual Studio 16 2019        = Generates Visual Studio 2019 project files.
                                 Use -A option to specify architecture.
  Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 11 2012 [arch] = Generates Visual Studio 2012 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 10 2010 [arch] = Generates Visual Studio 2010 project files.
                                 Optional [arch] can be "Win64" or "IA64".
  Visual Studio 9 2008 [arch]  = Generates Visual Studio 2008 project files.
                                 Optional [arch] can be "Win64" or "IA64".
...

**Comment by rhabacker** [comment]
> Just a question: Why are you maintaining this additional build system when you can use cmake to generate this on the fly ?
Please see https://github.com/dlfcn-win32/dlfcn-win32/pull/82 for a related fix.

**Comment by traversaro** [comment]
> > vxproj
> 
> Just a question: Why are you maintaining this additional build system when you can use cmake to generate this on the fly ?

I am not the person that added those projects in the first place, but given my experience is that those projects were meant for people that wanted to integrate  `dlfcn-win32` in their `msbuild`-based projects, without passing via CMake. The CMake-generated msbuild projects are not suitable for this as they contain several references to the CMake executable, and so they can't be used if CMake is not installed.

**Comment by traversaro** [comment]
I looked a bit into these changes and I am ok with it, as long as we rebase on top of https://github.com/dlfcn-win32/dlfcn-win32/pull/80 to ensure that the Make-based build system is still working correctly. 

> While working on this I recognized minor issues, which I fixed also with this pr.

If you happen to remember which minor issues you fixed it would be great if  you could mention it, thanks!

**Comment by rhabacker** [comment]
> I looked a bit into these changes and I am ok with it, as long as we rebase on top of #80 to ensure that the Make-based build system is still working correctly.

Will #80 also be applied to the `maint` branch ? I'm asking because pr  #72 is currently based on `maint` and depends on this pr. 

> If you happen to remember which minor issues you fixed it would be great if you could mention it, thanks!

It is a separate commit - see  242f781 `Fix cmake warning 'No project() command is present' - should I open a separate pr ?

**Comment by traversaro** [comment]
> It is a separate commit - see 242f781 `Fix cmake warning 'No project() command is present' - should I open a separate pr ?

Thanks, I had missed it, sorry for that. No need for a separate PR.

**Comment by traversaro** [comment]
> > I looked a bit into these changes and I am ok with it, as long as we rebase on top of #80 to ensure that the Make-based build system is still working correctly.
> 
> Will #80 also be applied to the `maint` branch ? I'm asking because pr #72 is currently based on `maint` and depends on this pr.

What is the `maint` branch? As far as I can see all the mentioned PR are against `dlfcn-win32:master`, but probably I am missing something.

**Comment by rhabacker** [comment]
> What is the `maint` branch? As far as I can see all the mentioned PR are against `dlfcn-win32:master`, but probably I am missing something.

Sorry for the confusion - you are correct. I There is no 'maint' branch, the one with 'maint' refers to another project I am working on in parallel

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
Thanks @rhabacker !

**Pull request merged**
