### PR TITLE
Turn off GUI error messages around LoadLibraryA also in test

### PR DESCRIPTION
**Pull request by pali**
Otherwise running test show GUI error messages which needs to be closed.

### CODE REVIEW

**Comment by pali** [comment]
Hi @traversaro! Can you look at this one PR?

**Comment by pali** [comment]
@traversaro ping

**Comment by traversaro** [comment]
Thanks! Just to understand, why test were successfull on AppVeyor? In that environment the windows are never opened in any case?

**Comment by pali** [comment]
I do not know. Probably there is some global windows settings to disable these popups and AppVeyor use it (for good reason).

**Comment by traversaro** [comment]
Thanks again.

**Pull request merged**
