### PR TITLE
cmake: use CROSSCOMPILING_EMULATOR

### PR DESCRIPTION
**Pull request by xantares**
it's a cmake built-in idiom that simplifies wrapping of wine, so no need for WINE_EXECUTABLE etc

### CODE REVIEW

**Comment by xantares** [comment]
@traversaro what do you say about this one ?

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
Ok for me, pinging @rhabacker and @pali if they have any objection.

**Comment by rhabacker** [comment]
I suggest to add the following cmake code to the top level CMakeLists.txt to give users a hint if the emulator is not available.
```
if(BUILD_TESTS AND CMAKE_CROSSCOMPILING_EMULATOR)
    list(GET CMAKE_CROSSCOMPILING_EMULATOR 0 WRAPPER)
    find_program(WRAPPER_FOUND ${WRAPPER})
    if(NOT WRAPPER_FOUND)
        message(FATAL_ERROR "Running cross-compiled tests requested, but requirements are not met.")
    endif()
endif()
```

**Comment by rhabacker** [comment]
Also a hint added to Readme.md for this support would be nice.

**Comment by traversaro** [comment]
@rhabacker are you sure that `find_program` will work fine when asked to found command with its full path?

**Comment by rhabacker** [comment]
The cmake doc says nothing about this, but the code shows it does https://github.com/Kitware/CMake/blob/eeb771e4d6b9a1127a0818a211cafb722a2dc387/Source/cmFindProgramCommand.cxx#L93

**Comment by rhabacker** [comment]
If you are concerned about using an undocumented function, the code can be changed to 

```
f(BUILD_TESTS AND CMAKE_CROSSCOMPILING_EMULATOR)
    list(GET CMAKE_CROSSCOMPILING_EMULATOR 0 WRAPPER)
    get_filename_component(DIR ${WRAPPER} DIRECTORY)
    get_filename_component(FILE ${WRAPPER} NAME)
    find_program(_wrapper ${FILE} PATHS ${DIR})
    if(NOT _wrapper)
        message(FATAL_ERROR "Running cross-compiled tests requested, but requirements are not met.")
    endif()
endif()
```

**Comment by xantares** [comment]
done, it's probably easier to check for CMAKE_CROSSCOMPILING_EMULATOR

note that its not even mandatory if you have binfmt

**Review by traversaro — APPROVED** [review]

**Pull request merged**
