### PR TITLE
Drop obsolete visual studio related files

### PR DESCRIPTION
**Pull request by rhabacker**
These files can be easily recreated with cmake on the fly, which is
already used by CI-system.

### CODE REVIEW

**Comment by traversaro** [comment]
Hi @rhabacker, as mentioned in https://github.com/dlfcn-win32/dlfcn-win32/pull/79#issuecomment-691633131 native msbuild projects are not exactly replaceable with CMake-generated one. 

Nevertheless, given that:
* after https://github.com/dlfcn-win32/dlfcn-win32/pull/51 integrating `dlfcn-win32` is just a matter of adding the `dlfcn.c` and `dlfcn.h` files to your Visual Studio project 
* No one is maintaining those Visual Studio projects, that are also relatively outdated w.r.t. to the latest Visual Studio version
* The Visual Studio projects are not tested by CI

I think we can safely remove them. 

What do you think @pali ?

**Comment by traversaro** [comment]
Hi @rhabacker, as mentioned in https://github.com/dlfcn-win32/dlfcn-win32/pull/79#issuecomment-691633131 native msbuild projects are not exactly replaceable with CMake-generated one. 

Nevertheless, given that:
* after https://github.com/dlfcn-win32/dlfcn-win32/pull/51 integrating `dlfcn-win32` is just a matter of adding the `dlfcn.c` and `dlfcn.h` files to your Visual Studio project 
* No one is maintaining those Visual Studio projects, that are also relatively outdated w.r.t. to the latest Visual Studio version
* The Visual Studio projects are not tested by CI

I think we can safely remove them. 

What do you think @pali ?

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
> after #51 integrating dlfcn-win32 is just a matter of adding the dlfcn.c and dlfcn.h files to your Visual Studio project

Actually, this is not completely correct, as you also need to make sure that `SHARED` is defined if you compile `dlfcn-win32` as part of a shared library. In any case, this should be document anyway as part of https://github.com/dlfcn-win32/dlfcn-win32/issues/83 .

**Comment by rhabacker** [comment]
The last push was a rebase with git master branch.

**Comment by traversaro** [comment]
Thanks @rhabacker !

**Pull request merged**
