### PR TITLE
Add Travis CI testing

### PR DESCRIPTION
**Pull request by pali**

### CODE REVIEW

**Comment by pali** [comment]
Great! Travis CI testing on Ubuntu with cross compiler and wine is working fine.

**Comment by traversaro** [comment]
Thanks! Ubuntu 16.04 is relatively old, but I think for this Linux CI the older the better.

**Review by traversaro — APPROVED** [review]

**Comment by TimothyGu** [comment]
Looks good, though do note that Travis CI's fate is a bit unclear, according to https://news.ycombinator.com/item?id=19218036 and others. We may want to migrate to GitHub Actions eventually.

**Comment by traversaro** [comment]
> Looks good, though do note that Travis CI's fate is a bit unclear, according to https://news.ycombinator.com/item?id=19218036 and others. We may want to migrate to GitHub Actions eventually.

Indeed, I personally migrated all my projects to GitHub Actions, let's see if there are any problems with Travis CI on a low traffic project such as `dlfcn-win32`, and if there are we will look into migrating to something else.

**Pull request merged**
