### PR TITLE
Add linked modules to a separate global list

### LINKED ISSUE #2: Can't load "printf" from "current process" address space
Migrated from https://code.google.com/p/dlfcn-win32/issues/detail?id=17

Originally reported by: @TooTallNate on Jun 8, 2014.

---

**What steps will reproduce the problem?**

  1. Download the attached `test.c` file
  2. Compile it against dlfcn-win32 (something like: cl.exe /I dlfcn-win32 dlfcn-win32\dlfcn.c test.c /Fetest.exe)
  3. Run `test.exe` and witness it failing to load "printf"

**What is the expected output? What do you see instead?**

  When I compile this code on OS X and Ubuntu, the `printf` symbol gets returned at line 17. When I compile it on Windows with dlfcn-win32, NULL is returned for `printf`. I would expect that the pointer to the printf function would be returned.

**What version of the product are you using? On what operating system?**

  Revision 38 on Windows XP Professional with SP3.

**Please provide any additional information below.**

  This test case is a simplified version of a failing test that was reported to me via CI on Windows. See: https://ci.appveyor.com/project/TooTallNate/node-dlfcn/build/13/job/96kayaf247q7byan

  Thanks in advance!

---

Attached `test.c`:

```c
/* Compile:
 *   Unix/OSX: gcc -ldl -o t test.c
 *   Windows via dlfcn-win32: cl.exe /I dlfcn-win32 dlfcn-win32\dlfcn.c test.c /Fetest.exe
 */

#include <dlfcn.h>
#include <stdio.h>

int main () {
  void *handle, *symbol;

  dlerror();
  handle = dlopen(NULL, RTLD_LAZY);
  printf("handle: %p\n", handle);

  dlerror();
  symbol = dlsym(handle, "printf");
  printf("symbol: %p\n", symbol);
  printf("dlerror() says: %s\n", dlerror());

  return 0;
}
```

### PR DESCRIPTION
**Pull request by TimothyGu**
Fixes #2.

TODO: add a DllMain function that automatically frees all objects even if `dlclose` is not called.

This literally took me almost half a year to figure out :/.

CC @TooTallNate, I'd appreciate it if you can review the code and check to see if this fixes the bug in nan.

### CODE REVIEW

**Comment by TooTallNate** [comment]
Wow that's awesome! I'll try to test it against the node-ffi test suite ASAP

**Comment by TimothyGu** [comment]
This patch adds quite a few global mutable states so it definitely needs some pairs of fresh eyes to see if it is possible to eliminate some.

**Comment by TooTallNate** [comment]
Preliminary test results are looking good! As a comparison:

__Before:__ https://ci.appveyor.com/project/TooTallNate/node-dlfcn/build/15/job/3fhy5mube5ayppak (1 failing test)

__Now:__ https://ci.appveyor.com/project/TooTallNate/node-dlfcn/build/17/job/pm25v1po2g460kad (0 failing tests!)

**Comment by TimothyGu** [comment]
Hm I saw this error in the logs:

```
..\..\..\deps\dlfcn-win32\dlfcn.c(220): warning C4018: '<' : signed/unsigned mismatch [C:\projects\node-dlfcn\build\deps\dlfcn-win32\dlfcn.vcxproj]
```

gotta investigate on how to fix that.

**Comment by TooTallNate** [comment]
:+1: That would be prudent

**Comment by TimothyGu** [comment]
@TooTallNate warning fixed, branch merged. Thanks for testing!

Next step: add AppVeyor support.

**Pull request closed without merging**
