### PR TITLE
Makefile: bug fix for test when wine not available

### PR DESCRIPTION
**Pull request by jannick0**

### CODE REVIEW

**Comment by traversaro** [comment]
Hi @jannick0 , thanks for the contribution. 
Can you briefly described on which operating system/with which configuration is this fix useful? Thanks!

**Comment by jannick0** [comment]
Sure - I am using a Windows 10 box and run into this issue.

**Comment by traversaro** [comment]
Sorry for the trouble @jannick0 , after merging https://github.com/dlfcn-win32/dlfcn-win32/pull/63 , it is needed to rebase the PR. 

Related to this PR instead, as I do not have a lot of experience in compiling `dlfcn-win32` on Linux, what do you think about this PR @pali ?

**Comment by pali** [comment]
Are `configure` and `Makefile` files working on Windows? If yes, then it should be extended in way that `wine` is never used/tried on windows and tests are started without wine. And on other platforms tests can be enabled only when wine is available.

**Comment by jannick0** [comment]
Would `wine` complain about `wine ./test.exe`? If not, then the fix would be very simple by prepending `./` to the test app.

**Comment by pali** [comment]
> Would `wine` complain about `wine ./test.exe`?

No, that is perfectly fine. You can either call `wine test.exe` or `wine ./test.exe`. But you *cannot* call just `./test.exe` as windows PE executables needs to be run under wine on Linux.

**Comment by jannick0** [comment]
The solution I was trying to allude to simply is `$(WINE) ./test` which would be fine for wine under linux and sh under Windows. Not sure if cmd was make' shell  - or are you considering this as an edge case?

**Comment by pali** [comment]
When `WINE` is not set by `configure` on non-Windows then you should not run just `./test.exe`. And seems that your change will do it.

**Comment by jannick0** [comment]
Which command would you expect to be run on non-Windows when `WINE` is **not** set? 
Currently it would be `test` which cannot be run for shells where curdir is not in PATH.  This is exactly the issue I was experiencing on Windows with make calling sh.  Would that be different on linux though?

**Comment by pali** [comment]
I mean, that running `make test` on Linux should always use wine. But when wine is not installed/not-available then patch in this pull request would run `make test` without wine. As you are checking if variable `WINE` is set or not and `configure` would unset `WINE` on Linux when wine is not installed.

**Comment by jannick0** [comment]
I think issues are conflated here. The minimal patch - now amended by simplification - is about cleaning up an issue in the recipe rule of the `makefile`. 
> I mean, that running `make test` on Linux should always use wine. 

As of now, this is a config issue to be addressed elsewhere I would propose.
> But when wine is not installed/not-available then patch in this pull request would run `make test` without wine.

Yes, given the status quo of `configure` and `makefile`, not due to any suggested patch version.   
> As you are checking if variable `WINE` is set or not and `configure` would unset `WINE` on Linux when wine is not installed.

As you say, this is directly connected with `configure`, but not with `makefile`.

**Comment by pali** [comment]
It is connected with both `configure` and `Makefile` files. Seems that empty value for `WINE` variable is used for two different things: 1) wine was not found and is required for running test and 2) wine should not be used for running test. So such logic cannot be implemented correctly.

I would rather introduce a new makefile variable for enabling/disabling tests (e.g. `WITH_TEST`) and then use `WINE` variable like you proposed. `configure` script needs to be fixed to set `WITH_TEST` correctly based on windows/non-windows platform and presence of wine.

Sounds good? Or is there any problem in this solution?

**Pull request closed without merging**
